### PR TITLE
enable Scala compiler flag '-Xcheckinit'

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ready for merge

**Comment by sullis** [comment]
ready for merge.

**Comment by jmcardon** [comment]
Did you run into any bugs that "-XcheckInit" solves?

**Comment by jmcardon** [comment]
For the record, I asked around, and bugs `-XcheckInit` prevents are checked at _runtime_.

It does not seem like a worthwhile flag to be honest.

**Pull request closed without merging**
