### PR TITLE
omg, quick before the lawyers find out!

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
ADD ALL THE SYMBOLS

**Comment by ChristopherDavenport** [comment]
I understand the sentiment, I think only Windows® is required by looking at the website.

**Comment by fommil** [comment]
oh shit, they found me, I don't know how, but they found me... the Windows® tests failed.

RRUUUUUUUUUNNNNNNN!!!!!!!

**Comment by jmcardon** [comment]
MERGING ANYWAY SAVE YOURSELVES

**Pull request merged**
