### PR TITLE
bump versions of many things

### PR DESCRIPTION
**Pull request by SethTisue**
the context for this is trying to add scala-pet-store to the Scala community build, over at https://github.com/scala/community-builds/pull/835

there are compile errors I lack the knowledge to fix. @hrhino is this something you'd be interested in tackling...? (I think @jmcardon is on hiatus)

note that in the community build context I don't need a release. I don't even need these changes merged on to master, I just need to have some branch somewhere that compiles that I can use. it's possible I could get the pet store app going just by hacking and slashing my way around this, but I figure it's worth asking if a proper fix could be done.

### CODE REVIEW

**Comment by SethTisue** [comment]
note that CI is failing with some Ruby stuff idk anything about.

at the moment, I'm only trying to get `tsec-http4s` going; the compile error there, currently, is

```
[error] /Users/tisue/tsec/tsec-http4s/src/test/scala/tsec/authentication/TSecAuthServiceTests.scala:41:13: value orNotFound is not a member of tsec.authentication.TSecAuthService[tsec.authentication.DummyUser,TSecAuthServiceTests.this.DummyAuthenticator,cats.effect.IO]
[error]     service.orNotFound(getSreq).unsafeRunSync().status mustBe Status.Ok
[error]             ^
[error] /Users/tisue/tsec/tsec-http4s/src/test/scala/tsec/authentication/TSecAuthServiceTests.scala:42:13: value orNotFound is not a member of tsec.authentication.TSecAuthService[tsec.authentication.DummyUser,TSecAuthServiceTests.this.DummyAuthenticator,cats.effect.IO]
[error]     service.orNotFound(postSreq).unsafeRunSync().status mustBe Status.Ok
[error]             ^
[error] two errors found
```

not sure if related to http4s upgrade or cats-effect upgrade or what.

perhaps there other compile errors will turn up in CI once the Ruby thing is fixed.

**Comment by SethTisue** [comment]
some tut weirdness

```
[info] [tut] compiling: /home/travis/build/jmcardon/tsec/docs/src/main/tut/motivation.md
[error] java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$9
[error] 	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.<init>(LambdaLift.scala:67)
[error] 	at scala.tools.nsc.transform.LambdaLift.newTransformer(LambdaLift.scala:49)
[error] 	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
```

**Comment by SethTisue** [comment]
some tut weirdness

```
[info] [tut] compiling: /home/travis/build/jmcardon/tsec/docs/src/main/tut/motivation.md
[error] java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$9
[error] 	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.<init>(LambdaLift.scala:67)
[error] 	at scala.tools.nsc.transform.LambdaLift.newTransformer(LambdaLift.scala:49)
[error] 	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
```

**Comment by ahjohannessen** [comment]
LGTM 👍

**Comment by zakpatterson** [comment]
A release now would be excellent.

**Comment by ChristopherDavenport** [comment]
I can see if I can get the ball rolling here.

**Pull request merged**
